# Part 3 — Introduction to Pandas

In this section, we move from numerical arrays to **structured data** using Pandas.

NumPy is ideal for numerical computation.  
Pandas is designed for **tabular data**, similar to spreadsheets or SQL tables.

Pandas provides two main data structures:

- `Series` → one-dimensional labeled data  
- `DataFrame` → two-dimensional labeled table  

Most real-world datasets are handled using DataFrames.

---

## Importing Pandas

In [2]:
import pandas as pd

---

# 1. Creating a Pandas Series

A Series is similar to a NumPy array, but with labels (index).

In [3]:
s = pd.Series([10, 20, 30, 40])
s

0    10
1    20
2    30
3    40
dtype: int64

Notice the index on the left.

You can also specify your own index.

In [4]:
s = pd.Series([10, 20, 30], index=["a", "b", "c"])
s

a    10
b    20
c    30
dtype: int64

Access elements using labels:

In [5]:
s["b"]

20

---

# 2. Creating a DataFrame

A DataFrame is a table with rows and columns.

## From a Dictionary

In [6]:
data = {
    "name": ["Alice", "Bob", "Charlie"],
    "age": [25, 30, 35],
    "score": [85, 90, 95]
}

df = pd.DataFrame(data)
df

      name  age  score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95

Each key becomes a column.

---

# 3. Inspecting Data

Pandas provides helpful inspection tools.

In [10]:
df.head(2)

    name  age  score
0  Alice   25     85
1    Bob   30     90

In [11]:
df.tail(2)

      name  age  score
1      Bob   30     90
2  Charlie   35     95

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   age     3 non-null      int64
 2   score   3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 200.0+ bytes

In [9]:
df.describe()

        age  score
count   3.0    3.0
mean   30.0   90.0
std     5.0    5.0
min    25.0   85.0
25%    27.5   87.5
50%    30.0   90.0
75%    32.5   92.5
max    35.0   95.0

- `head(N)` shows the first N rows  
- `tail(N)` shows the last N rows
- `info()` shows column types and missing values  
- `describe()` computes summary statistics  

---

# 4. Selecting Data

## Selecting a Column

In [12]:
df["age"]

0    25
1    30
2    35
Name: age, dtype: int64

## Selecting Multiple Columns

In [13]:
df[["name", "score"]]

      name  score
0    Alice     85
1      Bob     90
2  Charlie     95

## Selecting Rows with loc (label-based)

In [14]:
df.loc[0]

name     Alice
age         25
score       85
Name: 0, dtype: object

## Selecting Rows with iloc (position-based)

In [15]:
df.iloc[1]

name     Bob
age       30
score     90
Name: 1, dtype: object

---

# 5. Filtering Data

We can filter rows using conditions.

In [16]:
df[df["age"] > 28]

      name  age  score
1      Bob   30     90
2  Charlie   35     95

This selects only rows where age is greater than 28.

---

# 6. Adding and Modifying Columns

In [17]:
df["passed"] = df["score"] > 88
df

      name  age  score  passed
0    Alice   25     85   False
1      Bob   30     90    True
2  Charlie   35     95    True

You can also modify values:

In [18]:
df["age"] = df["age"] + 1
df

      name  age  score  passed
0    Alice   26     85   False
1      Bob   31     90    True
2  Charlie   36     95    True

---

# 7. Handling Missing Data

Let’s introduce missing values.

In [19]:
df.loc[1, "score"] = None
df

      name  age  score  passed
0    Alice   26   85.0   False
1      Bob   31    NaN    True
2  Charlie   36   95.0    True

Check for missing values:

In [20]:
df.isna()

    name    age  score  passed
0  False  False  False   False
1  False  False   True   False
2  False  False  False   False

In [21]:
df.isna().sum()

name      0
age       0
score     1
passed    0
dtype: int64

Drop missing values:

In [22]:
df.dropna()

      name  age  score  passed
0    Alice   26   85.0   False
2  Charlie   36   95.0    True

In [23]:
df.dropna(axis=1)

      name  age  passed
0    Alice   26   False
1      Bob   31    True
2  Charlie   36    True

By default, `dropna()` removes any row with at least one missing value. You can specify `axis=1` to drop columns instead.

Or fill them:

In [24]:
df["score"] = df["score"].fillna(df["score"].mean())
df

      name  age  score  passed
0    Alice   26   85.0   False
1      Bob   31   90.0    True
2  Charlie   36   95.0    True

---

# 8. Grouping Data

Grouping is very common in data analysis.

In [26]:
data = {
    "department": ["IT", "IT", "HR", "HR", "Finance"],
    "salary": [50000, 60000, 45000, 48000, 70000]
}

df2 = pd.DataFrame(data)
df2

  department  salary
0         IT   50000
1         IT   60000
2         HR   45000
3         HR   48000
4    Finance   70000

In [27]:
df2.groupby("department")["salary"].mean()

department
Finance    70000.0
HR         46500.0
IT         55000.0
Name: salary, dtype: float64

This computes the average salary per department.

---

# 9. Reading Data from a CSV File

In real projects, data comes from files.

Example:

In [28]:
# df = pd.read_csv("data/myfile.csv")

# Exercise Section

In this exercise, you will practice creating and manipulating a DataFrame.

## Part 1 — Create the Data

Create a DataFrame with:

- 10 rows
- 3 columns:
  - `student`
  - `grade`
  - `study_hours`

You can either:
- Manually define the data using a dictionary, or  
- Generate random values for grades and study hours.

---

## Part 2 — Compute Statistics

Using Pandas operations (without loops), compute:

1. The average grade  
2. The student with the highest grade  
3. The average number of study hours  

Hint:
- You may find `mean()` useful.
- You may find `idxmax()` useful.

---

## Part 3 — Feature Engineering

Add a new column called:

`passed`

The value should be:

- `True` if grade >= 50  
- `False` otherwise  

---

## Part 4 — Filtering

Create a new DataFrame containing only students who passed.

---

## Part 5 — Sorting

Sort the DataFrame by grade in descending order.

---

## Reflection Questions

- How many students passed?
- Is there a visible relationship between study hours and grade?
- What happens if you sort by study hours instead?

We will soon visualize these relationships to explore them further.

In [ ]:
# Your code goes here